from .system_prompts import (
    LOAN_ANALYZER_PROMPT,
    CREDIT_EVALUATOR_PROMPT,
    APPROVAL_DECISION_PROMPT,
    COMPLIANCE_CHECKER_PROMPT
)

__all__ = [
    "LOAN_ANALYZER_PROMPT",
    "CREDIT_EVALUATOR_PROMPT",
    "APPROVAL_DECISION_PROMPT",
    "COMPLIANCE_CHECKER_PROMPT"
]
